In [3]:
#Basic neuron code
inputs=[1.2,1.3,2.4]
weights=[2,3,5]
bias=3
output=inputs[0]*weights[0]+inputs[1]*weights[1]+inputs[2]*weights[2]+bias
print(output)

21.3


In [6]:
#Basic neuron code with 4 inputs
inputs=[1.2,1.3,2.4,3.3]
weights=[0.5,3.0,0.15,0.12]
bias=1
output=inputs[0]*weights[0]+inputs[1]*weights[1]+inputs[2]*weights[2]+inputs[3]*weights[3]+bias
print(output)

6.256


In [7]:
#3 neurons with 4 inputs
inputs=[1.2,1.3,2.4,3.3]
weights1=[0.5,3.0,0.15,0.12]
weights2=[2.0,0.83,-0.5,0.62]
weights3=[1.7,3.5,1.5,0.2]
bias=[1,2,3]
output=[inputs[0]*weights1[0]+inputs[1]*weights1[1]+inputs[2]*weights1[2]+inputs[3]*weights1[3]+bias[0],
         inputs[0]*weights2[0]+inputs[1]*weights2[1]+inputs[2]*weights2[2]+inputs[3]*weights2[3]+bias[1],
         inputs[0]*weights3[0]+inputs[1]*weights3[1]+inputs[2]*weights3[2]+inputs[3]*weights3[3]+bias[2]]
print(output)

[6.256, 6.324999999999999, 13.85]


In [12]:
#3 neurons with 4 inputs
inputs=[1.2,1.3,2.4,3.3]
weights=[[0.5,3.0,0.15,0.12],
         [2.0,0.83,-0.5,0.62],
         [1.7,3.5,1.5,0.2]]
biases=[1,2,3]
layer_outputs = []

for neuron_weights, neuron_bias in zip(weights, biases):
    neuron_output = 0
    for n_input, weight in zip(inputs, neuron_weights):
        neuron_output += n_input * weight
    neuron_output += neuron_bias  # Adding bias outside the inner loop
    layer_outputs.append(neuron_output)

print(layer_outputs)


[6.256, 6.324999999999999, 13.85]


In [18]:
#Basic neuron code with 4 inputs with numpy
import numpy as np

inputs = np.array([1.2, 1.3, 2.4, 3.3])
weights = np.array([[0.5, 3.0, 0.15, 0.12],
                    [2.0, 0.83, -0.5, 0.62],
                    [1.7, 3.5, 1.5, 0.2]])
biases = np.array([1, 2, 3]) 
output = np.dot(weights, inputs) + biases 
print(output)


[ 6.256  6.325 13.85 ]


In [21]:
#Basic neuron code for 3 examples and 4 features at input with 3 neurons and 4 inputs as there is 4 features with numpy
import numpy as np

inputs = np.array([[1.2, 1.3, 2.4, 3.3],
                 [1.2, 1.3, 2.4, 3.3],
                  [1.2, 1.3, 2.4, 3.3]])
weights = np.array([[0.5, 3.0, 0.15, 0.12],
                    [2.0, 0.83, -0.5, 0.62],
                    [1.7, 3.5, 1.5, 0.2]])
biases = np.array([1, 2, 3]) 
output = np.dot( inputs,weights.T) + biases 
print(output)


[[ 6.256  6.325 13.85 ]
 [ 6.256  6.325 13.85 ]
 [ 6.256  6.325 13.85 ]]


In [25]:
#two layer, 1 layer 1 with 4 neoron and layer 2 with 3 neurons, weight depend upon number of neurons
import numpy as np

inputs = np.array([[1.2, 1.3, 2.4, 3.3],
                   [1.2, 1.3, 2.4, 3.3],
                   [1.2, 1.3, 2.4, 3.3]])

weights1 = np.array([[0.5, 3.0, 0.15, 0.12],
                     [2.0, 0.83, -0.5, 0.62],
                     [1.7, 3.5, 1.5, 0.2]])
biases1 = np.array([1, 2, 3]) 

weights2 = np.array([[0.1, 0.2, 0.3],
                     [0.4, 0.5, 0.6],
                     [0.7, 0.8, 0.9]])
biases2 = np.array([0.1, 0.2, 0.3]) 

layer1_output = np.dot(inputs, weights1.T) + biases1 
layer2_output = np.dot(layer1_output, weights2.T) + biases2

print("Layer 1 output:")
print(layer1_output)
print("\nLayer 2 output:")
print(layer2_output)


Layer 1 output:
[[ 6.256  6.325 13.85 ]
 [ 6.256  6.325 13.85 ]
 [ 6.256  6.325 13.85 ]]

Layer 2 output:
[[ 6.1456 14.1749 22.2042]
 [ 6.1456 14.1749 22.2042]
 [ 6.1456 14.1749 22.2042]]


In [36]:
import numpy as np
np.random.seed(0)

X = np.array([[1.2, 1.3, 2.4, 3.3],
                   [1.2, 1.3, 2.4, 3.3],
                   [1.2, 1.3, 2.4, 3.3]])
class layer_dense:
    def __init__(self,n_inputs, n_neurons):
        self.weights= 0.10*np.random.randn(n_inputs, n_neurons)
        self.biases=np.zeros((1,n_neurons))
    def forward(self,inputs):
        self.ouput=np.dot(inputs, self.weights) + self.biases
        
        
layer1=layer_dense(4,5)  #object1
layer2=layer_dense(5,2)  #abject2

layer1.forward(X)
layer2.forward(layer1.ouput)
    
    
print('layer 1:',layer1.ouput)
print('layer 2:',layer2.ouput)

layer 1: [[0.22932314 1.0136021  0.21271895 0.38800308 0.10216035]
 [0.22932314 1.0136021  0.21271895 0.38800308 0.10216035]
 [0.22932314 1.0136021  0.21271895 0.38800308 0.10216035]]
layer 2: [[ 0.09478982 -0.0834259 ]
 [ 0.09478982 -0.0834259 ]
 [ 0.09478982 -0.0834259 ]]


In [7]:
#adding activation function
import numpy as np
np.random.seed(0)
import nnfs
from nnfs.datasets import spiral_data
'''
def spiral_data(points, classes):
X = np.zeros((points*classes, 2))
y = np.zeros(points*classes, dtype='uint8')
for class_number in range(classes):
ix = range(points*class_number, points*(class_number+1))
r = np.linspace(0.0, 1, points)  # radius
t = np.linspace(class_number*4, (class_number+1)*4, points) + np.random.randn(points)*0.2
X[ix] = np.c_[r*np.sin(t*2.5), r*np.cos(t*2.5)]
y[ix] = class_number
return X, y
'''
nnfs.init()

X, y = spiral_data(100, 3)   
'''
X = np.array([[1.2, 1.3, 2.4, 3.3],
              [1.2, 1.3, 2.4, 3.3],
             [1.2, 1.3, 2.4, 3.3]])
'''
class layer_dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

class Activation_ReLU:  
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)  

layer1 = layer_dense(2, 5)  # object1
Activation1 = Activation_ReLU()

layer1.forward(X)
print('layer 1:', layer1.output)
Activation1.forward(layer1.output)
print('After Activation Fuction:', Activation1.output)



layer 1: [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [-8.35815910e-04 -7.90404272e-04 -1.33452227e-03  4.65504505e-04
   4.56846210e-05]
 [-2.39994470e-03  5.93469958e-05 -2.24808278e-03  2.03573116e-04
   6.10024377e-04]
 ...
 [ 1.13291524e-01 -1.89262271e-01 -2.06855070e-02  8.11079666e-02
  -6.71350807e-02]
 [ 1.34588361e-01 -1.43197834e-01  3.09493970e-02  5.66337556e-02
  -6.29687458e-02]
 [ 1.07817926e-01 -2.00809643e-01 -3.37579325e-02  8.72561932e-02
  -6.81458861e-02]]
After Activation Fuction: [[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 4.65504505e-04
  4.56846210e-05]
 [0.00000000e+00 5.93469958e-05 0.00000000e+00 2.03573116e-04
  6.10024377e-04]
 ...
 [1.13291524e-01 0.00000000e+00 0.00000000e+00 8.11079666e-02
  0.00000000e+00]
 [1.34588361e-01 0.00000000e+00 3.09493970e-02 5.66337556e-02
  0.00000000e+00]
 [1.07817926e-01 0.00000000e+00 0.00000000e+

In [14]:
#For Softmax
import numpy as np
import math
import nnfs
nnfs.init
layer_outputs=[[4.8,3.2,0.9],
              [8.9,-0.4,13.9],
              [6.7,9.2,-5.5]]

#E=math.e

exp_values =np.exp(layer_outputs)
print('exp_values:',exp_values)

norm_values=(exp_values/np.sum(exp_values, axis=1, keepdims=True))
print('norm_values:',norm_values)

exp_values: [[1.21510418e+02 2.45325302e+01 2.45960311e+00]
 [7.33197354e+03 6.70320046e-01 1.08816136e+06]
 [8.12405825e+02 9.89712906e+03 4.08677144e-03]]
norm_values: [[8.18237915e-01 1.65199386e-01 1.65626994e-02]
 [6.69284683e-03 6.11888378e-07 9.93306541e-01]
 [7.58581511e-02 9.24141467e-01 3.81601061e-07]]


In [19]:
#adding activation function
import numpy as np
np.random.seed(0)
import nnfs
from nnfs.datasets import spiral_data

nnfs.init()

class layer_dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

class Activation_ReLU:  
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)
        
        
class Activation_softmax:
    def forward(self, inputs):
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
        self.output = probabilities

X, y = spiral_data(samples=100,classes= 3)        
        
dense1 = layer_dense(2, 3)  # object1
Activation1 = Activation_ReLU()

dense2 = layer_dense(3,3)  # object1
Activation2 = Activation_softmax()

dense1.forward(X)
Activation1.forward(dense1.output)

dense2.forward(Activation1.output)
Activation2.forward(dense2.output)

print(Activation2.output)


[[0.33333334 0.33333334 0.33333334]
 [0.33331734 0.33331832 0.33336434]
 [0.3332888  0.33329153 0.33341965]
 [0.33325943 0.33326396 0.33347666]
 [0.33323312 0.33323926 0.33352762]
 [0.33328417 0.33328718 0.33342862]
 [0.33318216 0.33319145 0.33362636]
 [0.3331828  0.33319202 0.33362517]
 [0.33314925 0.33316055 0.3336902 ]
 [0.3331059  0.33311984 0.33377427]
 [0.33308133 0.3330968  0.33382186]
 [0.33311024 0.33312503 0.33376473]
 [0.33305368 0.33307084 0.33387548]
 [0.33300948 0.33302936 0.3339612 ]
 [0.33301342 0.33303306 0.33395353]
 [0.33299848 0.33301902 0.3339825 ]
 [0.33312678 0.33318865 0.3336846 ]
 [0.3329409  0.33296496 0.33409408]
 [0.3329943  0.33303145 0.33397427]
 [0.33287367 0.33290187 0.33422443]
 [0.3328757  0.33290374 0.33422053]
 [0.33309552 0.33318356 0.33372095]
 [0.33317602 0.33328283 0.3335411 ]
 [0.332894   0.33293876 0.33416727]
 [0.33256376 0.33270204 0.3347342 ]
 [0.33281362 0.33284548 0.3343409 ]
 [0.33314452 0.33327034 0.33358508]
 [0.3331285  0.333258   0.33

In [21]:
import numpy as np
import math
b=5.2

print(np.log(b))
print(math.e**1.6486586255873816)

1.6486586255873816
5.199999999999999


In [22]:
import math
softmax_output=[0.7,0.4,2.3]
target_output=[1,0,0]
target_class = 0
loss=-(math.log(softmax_output[0])*target_output[0]+
       math.log(softmax_output[1])*target_output[1]+
       math.log(softmax_output[2])*target_output[2])
print(loss)

0.35667494393873245


In [25]:
#adding activation function
import numpy as np
np.random.seed(0)
import nnfs
from nnfs.datasets import spiral_data

nnfs.init()

class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

class Activation_ReLU:  
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)
        
        
class Activation_Softmax:
    def forward(self, inputs):
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
        self.output = probabilities
        
        
        
class Loss:
    def calculate(self, output, y):
        sample_losses = self.forward(output, y)
        data_loss = np.mean(sample_losses)
        return data_loss

class Loss_CategoricalCrossentropy(Loss):
    def forward(self, y_pred, y_true):
        samples = len(y_pred)
        y_pred_clipped = np.clip(y_pred, 1e-7, 1-1e-7)

        if len(y_true.shape) == 1:
            correct_confidences = y_pred_clipped[range(samples), y_true]

        elif len(y_true.shape) == 2:
            correct_confidences = np.sum(y_pred_clipped*y_true, axis=1)

        negative_log_likelihoods = -np.log(correct_confidences)
        return negative_log_likelihoods


    
X, y = spiral_data(samples=100, classes=3)

dense1 = Layer_Dense(2,3)
activation1 = Activation_ReLU()

dense2 = Layer_Dense(3, 3)
activation2 = Activation_Softmax()

dense1.forward(X)
activation1.forward(dense1.output)

dense2.forward(activation1.output)
activation2.forward(dense2.output)

print(activation2.output[:5])

loss_function = Loss_CategoricalCrossentropy()
loss = loss_function.calculate(activation2.output, y)

print("Loss:", loss)

[[0.33333334 0.33333334 0.33333334]
 [0.33331734 0.33331832 0.33336434]
 [0.3332888  0.33329153 0.33341965]
 [0.33325943 0.33326396 0.33347666]
 [0.33323312 0.33323926 0.33352762]]
Loss: 1.098445
