In [3]:
#Basic neuron code
inputs=[1.2,1.3,2.4]
weights=[2,3,5]
bias=3
output=inputs[0]*weights[0]+inputs[1]*weights[1]+inputs[2]*weights[2]+bias
print(output)

21.3


In [6]:
#Basic neuron code with 4 inputs
inputs=[1.2,1.3,2.4,3.3]
weights=[0.5,3.0,0.15,0.12]
bias=1
output=inputs[0]*weights[0]+inputs[1]*weights[1]+inputs[2]*weights[2]+inputs[3]*weights[3]+bias
print(output)

6.256


In [7]:
#3 neurons with 4 inputs
inputs=[1.2,1.3,2.4,3.3]
weights1=[0.5,3.0,0.15,0.12]
weights2=[2.0,0.83,-0.5,0.62]
weights3=[1.7,3.5,1.5,0.2]
bias=[1,2,3]
output=[inputs[0]*weights1[0]+inputs[1]*weights1[1]+inputs[2]*weights1[2]+inputs[3]*weights1[3]+bias[0],
         inputs[0]*weights2[0]+inputs[1]*weights2[1]+inputs[2]*weights2[2]+inputs[3]*weights2[3]+bias[1],
         inputs[0]*weights3[0]+inputs[1]*weights3[1]+inputs[2]*weights3[2]+inputs[3]*weights3[3]+bias[2]]
print(output)

[6.256, 6.324999999999999, 13.85]


In [12]:
#3 neurons with 4 inputs
inputs=[1.2,1.3,2.4,3.3]
weights=[[0.5,3.0,0.15,0.12],
         [2.0,0.83,-0.5,0.62],
         [1.7,3.5,1.5,0.2]]
biases=[1,2,3]
layer_outputs = []

for neuron_weights, neuron_bias in zip(weights, biases):
    neuron_output = 0
    for n_input, weight in zip(inputs, neuron_weights):
        neuron_output += n_input * weight
    neuron_output += neuron_bias  # Adding bias outside the inner loop
    layer_outputs.append(neuron_output)

print(layer_outputs)


[6.256, 6.324999999999999, 13.85]


In [18]:
#Basic neuron code with 4 inputs with numpy
import numpy as np

inputs = np.array([1.2, 1.3, 2.4, 3.3])
weights = np.array([[0.5, 3.0, 0.15, 0.12],
                    [2.0, 0.83, -0.5, 0.62],
                    [1.7, 3.5, 1.5, 0.2]])
biases = np.array([1, 2, 3]) 
output = np.dot(weights, inputs) + biases 
print(output)


[ 6.256  6.325 13.85 ]


In [21]:
#Basic neuron code for 3 examples and 4 features at input with 3 neurons and 4 inputs as there is 4 features with numpy
import numpy as np

inputs = np.array([[1.2, 1.3, 2.4, 3.3],
                 [1.2, 1.3, 2.4, 3.3],
                  [1.2, 1.3, 2.4, 3.3]])
weights = np.array([[0.5, 3.0, 0.15, 0.12],
                    [2.0, 0.83, -0.5, 0.62],
                    [1.7, 3.5, 1.5, 0.2]])
biases = np.array([1, 2, 3]) 
output = np.dot( inputs,weights.T) + biases 
print(output)


[[ 6.256  6.325 13.85 ]
 [ 6.256  6.325 13.85 ]
 [ 6.256  6.325 13.85 ]]


In [25]:
#two layer, 1 layer 1 with 4 neoron and layer 2 with 3 neurons, weight depend upon number of neurons
import numpy as np

inputs = np.array([[1.2, 1.3, 2.4, 3.3],
                   [1.2, 1.3, 2.4, 3.3],
                   [1.2, 1.3, 2.4, 3.3]])

weights1 = np.array([[0.5, 3.0, 0.15, 0.12],
                     [2.0, 0.83, -0.5, 0.62],
                     [1.7, 3.5, 1.5, 0.2]])
biases1 = np.array([1, 2, 3]) 

weights2 = np.array([[0.1, 0.2, 0.3],
                     [0.4, 0.5, 0.6],
                     [0.7, 0.8, 0.9]])
biases2 = np.array([0.1, 0.2, 0.3]) 

layer1_output = np.dot(inputs, weights1.T) + biases1 
layer2_output = np.dot(layer1_output, weights2.T) + biases2

print("Layer 1 output:")
print(layer1_output)
print("\nLayer 2 output:")
print(layer2_output)


Layer 1 output:
[[ 6.256  6.325 13.85 ]
 [ 6.256  6.325 13.85 ]
 [ 6.256  6.325 13.85 ]]

Layer 2 output:
[[ 6.1456 14.1749 22.2042]
 [ 6.1456 14.1749 22.2042]
 [ 6.1456 14.1749 22.2042]]


In [36]:
import numpy as np
np.random.seed(0)

X = np.array([[1.2, 1.3, 2.4, 3.3],
                   [1.2, 1.3, 2.4, 3.3],
                   [1.2, 1.3, 2.4, 3.3]])
class layer_dense:
    def __init__(self,n_inputs, n_neurons):
        self.weights= 0.10*np.random.randn(n_inputs, n_neurons)
        self.biases=np.zeros((1,n_neurons))
    def forward(self,inputs):
        self.ouput=np.dot(inputs, self.weights) + self.biases
        
        
layer1=layer_dense(4,5)  #object1
layer2=layer_dense(5,2)  #abject2

layer1.forward(X)
layer2.forward(layer1.ouput)
    
    
print('layer 1:',layer1.ouput)
print('layer 2:',layer2.ouput)

layer 1: [[0.22932314 1.0136021  0.21271895 0.38800308 0.10216035]
 [0.22932314 1.0136021  0.21271895 0.38800308 0.10216035]
 [0.22932314 1.0136021  0.21271895 0.38800308 0.10216035]]
layer 2: [[ 0.09478982 -0.0834259 ]
 [ 0.09478982 -0.0834259 ]
 [ 0.09478982 -0.0834259 ]]


In [7]:
#adding activation function
import numpy as np
np.random.seed(0)
import nnfs
from nnfs.datasets import spiral_data
'''
def spiral_data(points, classes):
X = np.zeros((points*classes, 2))
y = np.zeros(points*classes, dtype='uint8')
for class_number in range(classes):
ix = range(points*class_number, points*(class_number+1))
r = np.linspace(0.0, 1, points)  # radius
t = np.linspace(class_number*4, (class_number+1)*4, points) + np.random.randn(points)*0.2
X[ix] = np.c_[r*np.sin(t*2.5), r*np.cos(t*2.5)]
y[ix] = class_number
return X, y
'''
nnfs.init()

X, y = spiral_data(100, 3)   
'''
X = np.array([[1.2, 1.3, 2.4, 3.3],
              [1.2, 1.3, 2.4, 3.3],
             [1.2, 1.3, 2.4, 3.3]])
'''
class layer_dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

class Activation_ReLU:  
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)  

layer1 = layer_dense(2, 5)  # object1
Activation1 = Activation_ReLU()

layer1.forward(X)
print('layer 1:', layer1.output)
Activation1.forward(layer1.output)
print('After Activation Fuction:', Activation1.output)



layer 1: [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [-8.35815910e-04 -7.90404272e-04 -1.33452227e-03  4.65504505e-04
   4.56846210e-05]
 [-2.39994470e-03  5.93469958e-05 -2.24808278e-03  2.03573116e-04
   6.10024377e-04]
 ...
 [ 1.13291524e-01 -1.89262271e-01 -2.06855070e-02  8.11079666e-02
  -6.71350807e-02]
 [ 1.34588361e-01 -1.43197834e-01  3.09493970e-02  5.66337556e-02
  -6.29687458e-02]
 [ 1.07817926e-01 -2.00809643e-01 -3.37579325e-02  8.72561932e-02
  -6.81458861e-02]]
After Activation Fuction: [[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 4.65504505e-04
  4.56846210e-05]
 [0.00000000e+00 5.93469958e-05 0.00000000e+00 2.03573116e-04
  6.10024377e-04]
 ...
 [1.13291524e-01 0.00000000e+00 0.00000000e+00 8.11079666e-02
  0.00000000e+00]
 [1.34588361e-01 0.00000000e+00 3.09493970e-02 5.66337556e-02
  0.00000000e+00]
 [1.07817926e-01 0.00000000e+00 0.00000000e+